Arch:
  name: enet
  num_classes: 4

Optim:
  name: Adam
  lr: 0.01

Scheduler:
  name: MultiStepLR
  milestones: [1,2,3,4]

Dataset:
  root_dir: "'../dataset/ACDC-all'"
  subfolders: ['img','gt']
  transform: segment_transform((224,224))
  #  augment: PILaugment
  pin_memory: False

Dataloader:
  batch_size: 8
  num_workers: 8
  shuffle: True
  #  batch_sampler: [PatientSampler,
  #                  {grp_regex: '(patient\d+_\d+)_\d+',shuffle: False}]
  batch_sampler: None

Trainer:
  max_epoch: 30
  save_dir: tmp/run
  save_train: True
  save_val: True
  device: cuda
  axises: [0,1,2, 3]
  metricname: test.csv
  checkpoint: tmp/run/best.pth

Loss:
  name: cross_entropy
  weight: [0.1, 1, 1, 2]


