Arch:
  name: deeplabv3
  num_classes: 19

Optim:
  name: Adam
  lr: 0.0005

Scheduler:
  name: MultiStepLR
  milestones: [10,20,30,40,50,60,70,80,90]
  gamma: 0.7


Dataset:
  root_dir: /home/jizong/Workspace/ReproduceAdaptSegNet/data/Cityscapes/data
  image_size: ( 256, 512 )
  augmentations:
#    rcrop: [200, 200]                                #[crop of size (h,w)]
#    rotate: 10                                    #[rotate -d to d degrees]
#    scale: [256,256]                                 #[scale to size (h,w)]
#    ccrop: [224,224]                                 #[center crop of (h,w)]

Dataloader:
  pin_memory: False
  batch_size: 4
  num_workers: 4
  shuffle: True
  drop_last: True

Trainer:
  max_epoch: 100
  save_dir: tmp/cityscape
  device:  cuda
#  axises: [0,1,2,3,4,5,6,7]
  metricname: metrics.csv
  checkpoint: tmp/cityscape/best.pth


Loss:
  name: cross_entropy
  ignore_index: 255

StartTraining:
  save_train: False
  save_val: False