'#Trainer':
  checkpoint_path: runs/spleen/1/baseline
Adv_Scheduler:
  begin_epoch: 20
  max_epoch: 50
  max_value: 0.05
  name: RampScheduler
  ramp_mult: -5
Adv_Training:
  eplision: 0.03
Arch:
  name: enet
  num_classes: 2
Config: config/spleen_config_cotraing.yaml
Cot_Scheduler:
  begin_epoch: 0
  max_epoch: 50
  max_value: 0.5
  name: RampScheduler
  ramp_mult: -5
Dataset:
  augment: PILaugment
  pin_memory: false
  root_dir: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - jizong
  - Workspace
  - Deep-Co-Training-for-Semi-Supervised-Image-Segmentation
  - dataset
  - Spleen
  subfolders:
  - img
  - gt
  transform: segment_transform((256,256))
Lab_Dataloader:
  batch_sampler:
  - PatientSampler
  - grp_regex: Patient_\d+
    shuffle: false
  batch_size: 4
  drop_last: true
  num_workers: 4
  pin_memory: false
  shuffle: true
Lab_Partitions:
  num_models: 2
  partition_overlap: 1
  partition_sets: 0.5
Loss:
  name: cross_entropy
  weight:
  - 1
  - 1
Optim:
  lr: 0.001
  name: Adam
  weight_decay: 0.0001
Scheduler:
  gamma: 0.1
  name: StepLR
  step_size: 90
Seed: 1
StartTraining:
  augment_labeled_data: true
  augment_unlabeled_data: true
  save_train: false
  save_val: false
  train_adv: false
  train_jsd: false
Trainer:
  axises:
  - 0
  - 1
  device: cuda:0
  max_epoch: 1
  metricname: metrics.csv
  save_dir: spleen/1/baseline
  use_tqdm: true
Unlab_Dataloader:
  batch_size: 4
  drop_last: true
  num_workers: 4
  pin_memory: false
  shuffle: true
