Arch:
  name: enet
  num_classes: 4

Optim:
  name: Adam
  lr: 0.0005
#  weight_decay: 0.00002

Scheduler:
  name: MultiStepLR
  milestones: [10, 20, 30, 40, 50, 60, 70, 90, 120, 150]
  gamma: 0.7


Dataset:
  root_dir: dataset/ACDC-all
  subfolders: ['img','gt']
  transform: segment_transform((256,256))
  augment: None
  pin_memory: False

Lab_Dataloader:
  pin_memory: False
  batch_size: 2
  num_workers: 2
  shuffle: True
  drop_last: True
#  batch_sampler: [PatientSampler,
#                  {grp_regex: '(patient\d+_\d+)_\d+',shuffle: False}]

Lab_Partitions:
  label: [[1,101],[1,101]]
  unlabel: [50,100]


Unlab_Dataloader:
  pin_memory: False
  batch_size: 2
  num_workers: 2
  shuffle: True
  drop_last: True

Trainer:
  max_epoch: 120
  save_dir: tmp/ACDC_cotraining
  device: cuda:0
  axises: [1,2,3]
  metricname: metrics.csv
  lambda_cot_max: 1
  lambda_adv_max: 0.005
  ramp_up_mult: -5
  epoch_max_ramp: 100

Loss:
  name: cross_entropy
  weight: [1, 1, 1, 1]

StartTraining:
  train_jsd: False
  train_adv: False
  save_train: False
  save_val: True
  augment_labeled_data: False
  augment_unlabeled_data: False